site_name: streamOS
nav:
  - Home: index.md
  - Platform:
    - The streamOS Bot: bot.md
    - Simulations: simulations.md
    - Integrations: integrations.md
    - Reconciliation: reconciliation.md
  - Contract2Cash:
    - Introduction: about.md
    - Overview: overview.md
    - Customer Object: customer.md
    - Product Object: product.md
    - Contract Object: contracts.md
    - Usage Object: usage.md
    - Invoice Object: invoice.md
    - FAQ & How-To: faq.md
    - Users: users.md
    - Developer Documentation: 
      - Swagger: "https://api.streamos.io/swagger-ui"
      - How-To: api-howto.md
theme: 
  name: readthedocs
